# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('reporter', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('done_date', models.DateTimeField(null=True)),
                ('severity', models.CharField(choices=[(1, 'Major'), (2, 'Minor')], default='', max_length=100)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
